### ISSUE TITLE
AttributeError when calling from CLI, whatever the arguments

### ISSUE THREAD

**Issue by raffaem** [petermr/pygetpapers#32]
**Describe the bug**
```
$ pygetpapers -q "BONE METASTASES IN NEUROENDOCRINE TUMORS:"
Traceback (most recent call last):
  File "/home/raffaele/.local/bin/pygetpapers", line 8, in <module>
    sys.exit(main())
  File "/home/raffaele/.local/lib/python3.10/site-packages/pygetpapers/pygetpapers.py", line 538, in main
    callpygetpapers.handlecli()
  File "/home/raffaele/.local/lib/python3.10/site-packages/pygetpapers/pygetpapers.py", line 358, in handlecli
    default=self.default_url,
AttributeError: 'Pygetpapers' object has no attribute 'default_url'. Did you mean: 'default_path'?
```

**Expected behavior**
Should work

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 35

**Comment by vinitamehlawat** [comment]
Hi @ayush4921 

I am also facing the same issue, I have followed the installation instruction but whenever I tried to run the `pygetpapers --help` it gave me an error:  `AttributeError: **'Pygetpapers' object has no attribute 'default_url'`**.

Thanks
Vinita

**Comment by ayush4921** [comment]
Please update pygetpapers. The bug has been fixed in the latest update.
