### ISSUE TITLE
JOSS Review: Improve help message from the command-line tool

### ISSUE THREAD

**Issue by khinsen** [petermr/pygetpapers#38]
`pygetpapers -h` says, among other hints:

```
  -o OUTPUT, --output OUTPUT
                        output directory (Default: Folder inside current working
                        directory named )
```

From the observed behaviour, that should probably be ".. folder inside the current working directory whose name is the current date and time".

**Comment by ayush4921** [comment]
Thanks, a lot for pointing this out, I have edited the help text. It will get pushed in the next version release.

**Comment by khinsen** [comment]
Great! There's also a copy of it in the README.
