### ISSUE TITLE
Compatability errors when forcing upgrade/reinstall

### ISSUE THREAD

**Issue by mannyrules** [petermr/pygetpapers#45]
**Describe the bug**
Compatability errors when forcing upgrade/re-install

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
py4ami 0.0.45 requires numpy~=1.22.0, but you have numpy 1.24.0 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.0 which is incompatible.
docanalysis 0.2.0 requires lxml==4.7.1, but you have lxml 4.9.2 which is incompatible.
docanalysis 0.2.0 requires nltk==3.6.7, but you have nltk 3.8 which is incompatible.
docanalysis 0.2.0 requires pandas==1.3.4, but you have pandas 1.5.2 which is incompatible.
docanalysis 0.2.0 requires pytest==6.2.5, but you have pytest 7.2.0 which is incompatible.
docanalysis 0.2.0 requires tqdm==4.62.3, but you have tqdm 4.64.1 which is incompatible.
```

**To Reproduce**
launched venv
ran `pip install pygetpapers  --upgrade --force-reinstall`

**Expected behavior**
Should have installed everything it needed

**Desktop (please complete the following information):**
 - MacOS

**Comment by ayush4921** [comment]
@mannyrules This is a common error as at the type of pushing the current version, those were the library versions in use. Ideally docanalysis and pygetpapers should use > instead of == to demonstrate the versions of the libraries. I will create a new issue of pygetpapers to fix this.

**Comment by ayush4921** [comment]
I have created a new version. The same needs to be done for docanalysis

**Comment by petermr** [comment]
Thanks!!
That will help
