### ISSUE TITLE
could not run pygetpapers after downloading

### ISSUE THREAD

**Issue by tlhahsn** [petermr/pygetpapers#7]
i have cloned and downloaded pygetpapers but after downloading when i tried the command `pygetpapers --help` it gave the following error:
```
pygetpapers --help
'pygetpapers' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by petermr** [comment]
Please include all relevant output.

**Comment by tlhahsn** [comment]
C:\Users\talha>git clone https://github.com/petermr/pygetpapers
Cloning into 'pygetpapers'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (26/26), done.
Receiving objects:  55% (22/40)sed 28 (delta 2), pack-reused 0 eceiving objects:  52% (21/40)
Receiving objects: 100% (40/40), 28.05 KiB | 319.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
C:\Users\talha>python -m pip install git+git://github.com/petermr/pygetpapers
Collecting git+git://github.com/petermr/pygetpapers
  Cloning git://github.com/petermr/pygetpapers to c:\users\talha\appdata\local\temp\pip-req-build-62tn7k47
Requirement already satisfied (use --upgrade to upgrade): pygetpapers==0.0.1 from git+git://github.com/petermr/pygetpapers in c:\users\talha\appdata\roaming\python\python39\site-packages
Requirement already satisfied: requests in c:\users\talha\appdata\roaming\python\python39\site-packages (from pygetpapers==0.0.1) (2.25.1)
Requirement already satisfied: pandas_read_xml in c:\users\talha\appdata\roaming\python\python39\site-packages (from pygetpapers==0.0.1) (0.0.9)
Requirement already satisfied: pandas in c:\users\talha\appdata\roaming\python\python39\site-packages (from pygetpapers==0.0.1) (1.2.3)
Requirement already satisfied: lxml in c:\users\talha\appdata\roaming\python\python39\site-packages (from pygetpapers==0.0.1) (4.6.2)
Requirement already satisfied: chromedriver_autoinstaller in c:\users\talha\appdata\roaming\python\python39\site-packages (from pygetpapers==0.0.1) (0.2.2)
Requirement already satisfied: xmltodict in c:\users\talha\appdata\roaming\python\python39\site-packages (from pygetpapers==0.0.1) (0.12.0)
Requirement already satisfied: selenium in c:\users\talha\appdata\roaming\python\python39\site-packages (from pygetpapers==0.0.1) (3.141.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\talha\appdata\roaming\python\python39\site-packages (from requests->pygetpapers==0.0.1) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\talha\appdata\roaming\python\python39\site-packages (from requests->pygetpapers==0.0.1) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\talha\appdata\roaming\python\python39\site-packages (from requests->pygetpapers==0.0.1) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\talha\appdata\roaming\python\python39\site-packages (from requests->pygetpapers==0.0.1) (4.0.0)
Requirement already satisfied: pyarrow in c:\users\talha\appdata\roaming\python\python39\site-packages (from pandas_read_xml->pygetpapers==0.0.1) (3.0.0)
Requirement already satisfied: distlib in c:\users\talha\appdata\roaming\python\python39\site-packages (from pandas_read_xml->pygetpapers==0.0.1) (0.3.1)
Requirement already satisfied: zipfile36 in c:\users\talha\appdata\roaming\python\python39\site-packages (from pandas_read_xml->pygetpapers==0.0.1) (0.1.3)
Requirement already satisfied: pytz>=2017.3 in c:\users\talha\appdata\roaming\python\python39\site-packages (from pandas->pygetpapers==0.0.1) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\talha\appdata\roaming\python\python39\site-packages (from pandas->pygetpapers==0.0.1) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\talha\appdata\roaming\python\python39\site-packages (from pandas->pygetpapers==0.0.1) (1.20.1)
Requirement already satisfied: six>=1.5 in c:\users\talha\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7.3->pandas->pygetpapers==0.0.1) (1.15.0)
Using legacy 'setup.py install' for pygetpapers, since package 'wheel' is not installed.
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\talha\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
C:\Users\talha>pygetpapers --help
'pygetpapers' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ShweataNHegde** [comment]
Try the other listed methods, maybe? Check the documentation here: https://github.com/petermr/pygetpapers/wiki/Installation

**Comment by tlhahsn** [comment]
i have tried and downloaded the pygetpapers using different mentioned commands, still i could not run it
